# Generated by Django 5.2.6 on 2025-09-16 11:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EygarHost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('on_hold', 'On Hold')], default='draft', max_length=20)),
                ('current_step', models.CharField(choices=[('business_profile', 'Business Profile'), ('identity_verification', 'Identity Verification'), ('contact_details', 'Contact Details'), ('review_submission', 'Review Submission')], default='business_profile', max_length=30)),
                ('business_profile_completed', models.BooleanField(default=False)),
                ('identity_verification_completed', models.BooleanField(default=False)),
                ('contact_details_completed', models.BooleanField(default=False)),
                ('review_submission_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eygar_host', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eygar_hosts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('mobile_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")])),
                ('mobile_verified', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('mobile_verification_code', models.CharField(blank=True, max_length=6)),
                ('mobile_verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")])),
                ('whatsapp_verified', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('telegram_verified', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('facebook_page_url', models.URLField(blank=True)),
                ('facebook_verified', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('email_verified', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eygar_host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_details', to='eygarprofile.eygarhost')),
            ],
            options={
                'db_table': 'contact_details',
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('license_number', models.CharField(max_length=100)),
                ('license_document', models.FileField(help_text='Upload business license document', upload_to='licenses/%Y/%m/')),
                ('business_logo', models.ImageField(blank=True, null=True, upload_to='business_logos/%Y/%m/')),
                ('business_address_line1', models.CharField(max_length=255)),
                ('business_address_line2', models.CharField(blank=True, max_length=255)),
                ('business_city', models.CharField(max_length=100)),
                ('business_state', models.CharField(max_length=100)),
                ('business_postal_code', models.CharField(max_length=20)),
                ('business_country', models.CharField(max_length=100)),
                ('business_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eygar_host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='eygarprofile.eygarhost')),
            ],
            options={
                'db_table': 'business_profiles',
            },
        ),
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport')], max_length=20)),
                ('document_number', models.CharField(max_length=50)),
                ('document_image_front', models.ImageField(upload_to='identity_documents/%Y/%m/')),
                ('document_image_back', models.ImageField(blank=True, null=True, upload_to='identity_documents/%Y/%m/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('fathers_name', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('id_address_line1', models.CharField(blank=True, max_length=255)),
                ('id_address_line2', models.CharField(blank=True, max_length=255)),
                ('id_city', models.CharField(blank=True, max_length=100)),
                ('id_state', models.CharField(blank=True, max_length=100)),
                ('id_postal_code', models.CharField(blank=True, max_length=20)),
                ('id_country', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('eygar_host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_verification', to='eygarprofile.eygarhost')),
            ],
            options={
                'db_table': 'identity_verifications',
            },
        ),
        migrations.CreateModel(
            name='ProfileStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('change_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('eygar_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='eygarprofile.eygarhost')),
            ],
            options={
                'db_table': 'profile_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('additional_notes', models.TextField(blank=True, help_text='Any additional information for reviewers')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('privacy_policy_accepted', models.BooleanField(default=False)),
                ('eygar_host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_submission', to='eygarprofile.eygarhost')),
            ],
            options={
                'db_table': 'review_submissions',
            },
        ),
    ]
