# Generated by Django 5.2.6 on 2025-09-16 12:24

import eygarprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eygarprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to=eygarprofile.models.logo_upload_path),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='license_document',
            field=models.FileField(help_text='Upload business license document', upload_to=eygarprofile.models.license_upload_path),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='latitude',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='longitude',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
