# Generated by Django 5.2.6 on 2025-09-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eygarprofile', '0002_alter_businessprofile_business_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eygarhost',
            name='current_step',
            field=models.CharField(choices=[('business_profile', 'Business Profile'), ('identity_verification', 'Identity Verification'), ('contact_details', 'Contact Details'), ('review_submission', 'Review Submission'), ('completed', 'Completed')], default='business_profile', max_length=30),
        ),
    ]
