# Generated by Django 5.2.6 on 2025-10-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eygarprofile', '0002_vendorprofile_vendorcontactdetails_servicearea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='review_submission_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='current_step',
            field=models.CharField(choices=[('company_details', 'Company Details'), ('service_area', 'Service Area'), ('contact_details', 'Contact Details'), ('review_submission', 'Review Submission'), ('completed', 'Completed')], default='company_details', max_length=30),
        ),
    ]
