# Generated by Django 5.2.6 on 2025-10-29 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eygarprofile', '0003_vendorprofile_review_submission_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReviewVendorSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('additional_notes', models.TextField(blank=True, help_text='Any additional information for reviewers')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('privacy_policy_accepted', models.BooleanField(default=False)),
                ('eygar_vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_vendor_submission', to='eygarprofile.vendorprofile')),
            ],
            options={
                'db_table': 'review_vendor_submissions',
            },
        ),
    ]
