# Generated by Django 5.2.6 on 2025-12-17 08:42

import conf.storages
import eygarprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eygarprofile', '0004_vendorprofile_reviewed_at_vendorprofile_submitted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, storage=conf.storages.S3MediaStorage(), upload_to=eygarprofile.models.get_logo_upload_path),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='license_document',
            field=models.FileField(help_text='Upload business license document', storage=conf.storages.S3MediaStorage(), upload_to=eygarprofile.models.get_license_upload_path),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='document_image_back',
            field=models.ImageField(blank=True, null=True, storage=conf.storages.S3MediaStorage(), upload_to=eygarprofile.models.get_document_back_upload_path),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='document_image_front',
            field=models.ImageField(storage=conf.storages.S3MediaStorage(), upload_to=eygarprofile.models.get_document_front_upload_path),
        ),
    ]
