import os
import uuid

import boto3
from django.conf import settings
from django.core.files.storage import Storage
from django.utils.deconstruct import deconstructible


@deconstructible
class S3MediaStorage(Storage):
    """
    Custom storage for S3 to handle media file uploads.
    """

    def __init__(self):
        self.s3_client = boto3.client(
            "s3",
            aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
            aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
            region_name=settings.AWS_S3_REGION_NAME,
        )

    def _save(self, name, content):
        """
        This method is called by Django to save the file.
        'name' is the file path generated by the 'upload_to' callable.
        'content' is the file object itself.
        """
        extra_args = {
            "ACL": "public-read",
            "ContentType": getattr(content, "content_type", "application/octet-stream"),
        }

        self.s3_client.upload_fileobj(content, settings.AWS_S3_BUCKET_NAME, name, ExtraArgs=extra_args)

        return name

    def url(self, name):
        """
        Returns the public URL for the file.
        """
        return f"https://{settings.AWS_S3_CUSTOM_DOMAIN}/{name}"

    def exists(self, name):
        """
        Checks if a file with the given name already exists in the S3 bucket.
        """
        try:
            self.s3_client.head_object(Bucket=settings.AWS_S3_BUCKET_NAME, Key=name)
            return True
        except self.s3_client.exceptions.ClientError:
            return False

    def delete(self, name):
        """
        Deletes the specified file from the S3 bucket.
        """
        self.s3_client.delete_object(Bucket=settings.AWS_S3_BUCKET_NAME, Key=name)
